import Registration from '../components/registration';
import Head from 'next/head';
// import Login from '../components/login';

export default function Home() {
  return (
    <>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Registration />
      {/* <Login /> */}
    </>
  )
}
